### ISSUE TITLE
Database Model information

### ISSUE THREAD

**Issue by franckleveque** [telosys-tools-bricks/telosys-tools-database#2]
Hi,

I'm currenlty trying to transform a C# Dataset into your database model. However, I didn't find any explaination about the database model anywhere. Could you provide me some internal documentation on the schema and value you are using in there?

Some java specifics seems quite difficult to understand like the jdbcTypeCode in the column element.

Thanks in advance,

**Comment by l-gu** [comment]
what do you want to do exactly ?
create a new model with you own tool ?
if it is the case I advise you to create a DSL model, this kind of model is simpler than a 'DB Model'
If you just want to create a DB model from an existing database see : https://github.com/telosys-tools-bricks/telosys-cli/wiki/Guide-Step-2-DB-Model

**Comment by franckleveque** [comment]
Hi, 

Thanks for your answer. Fact is that I have an existing dataset schema. I have tried to rely on the guide provided, but I have not found any jdbc driver for ADO.Net dataset. 

As the ADO.net dataset schema is really close to a database description (it describe the tables and the relations between them), I thought it would be easier to perform the transformation using the db model than an object model.

**Comment by l-gu** [comment]
As far as I know ADO.Net Dataset is not really a database (?) So I don't think that it's possible to connect using a JDBC driver.
If you're able to  retrieve your schema description (in another way) you can have a look at the 'telosys-tools-repository' project to figure out the 'dbrep' file is built
